# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "Wuuu3511"
repo_name: "cv-arxiv-daily"
show_authors: True
show_links: True
show_badge: True
max_results: 10

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/cv-arxiv-daily.json'
json_gitpage_path: './docs/cv-arxiv-daily-web.json'
json_wechat_path: './docs/cv-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
# keywords to search
keywords:
    "SLAM": 
        filters: ["SLAM", "Visual Odometry"]
    "3DGS":
        filters: ["3DGS", "NeRF"]
    "3D Reconstruction":
        filters: ["DUST3R", "MVS", "Multi-view Stereo", "Point Cloud Reconstruction", "Depth Estimation", "Volumetric Reconstruction", "Mesh Reconstruction"]
    "3D Understanding":
        filters: ["3D understanding", "3D scene understanding", "Visual Grounding", "Open-vocabulary Segmentation", "3D Semantic Segmentation", "3D Object Detection", "3D Layout Estimation"]
    "VLM":
        filters: ["VLM", "Vision Language Model"]
